### ISSUE TITLE
i'm using laravel 5.5,, and when i try to do an auth, i have this error

### ISSUE THREAD

**Issue by danm-geronimo** [Parziphal/parse#12]
Exception (109)
You must call ParseClient::initialize() before making any requests.

**Comment by Parziphal** [comment]
Sorry for the late reply. Did you make sure `Parziphal\Parse\ParseServiceProvider::class` is in the `providers` in `config/app.php`?

**Comment by nowfalsalahudeen** [comment]
already did this
Parziphal\Parse\ParseServiceProvider::class is in the providers in config/app.php

but still getting error. i have attach the screenshots 
![screenshot from 2018-03-28 16-30-43](https://user-images.githubusercontent.com/4261741/38025339-a20a6720-32a5-11e8-903f-6b289fd488d5.png)
![screenshot from 2018-03-28 16-30-36](https://user-images.githubusercontent.com/4261741/38025341-a23c7e54-32a5-11e8-8370-14560bd070cc.png)

**Comment by Parziphal** [comment]
@nowfalsalahudeen are you getting the same error as the OP? I just tried logging in and it worked fine.
The error `You must call ParseClient::initialize() before making any requests.` indicates that there's a missconfiguration somewhere, because if this library is being loaded correctly, `ParseClient::initialize()` will be called.
