### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by mohamedbelhassen** [Parziphal/parse#8]
I folowed the setup instructions, but the process fails :+1: 

class Parziphal\Parse\ParseServiceProvider not found

Please tell me how to proceed step by step using a freshly installed Laravel website.

Cordially,
M.B

**Comment by Parziphal** [comment]
I'm sure the cause lies beyond the scope of the library, so I don't know what could be causing such error. It could be:

* The library is actually missing.
* Composer didn't register the class (I don't know if that's even possible).
* You have a customized setup.
* Maybe you're using Laravel 5.5? But that can't cause the class to be missing... or can it?

I haven't tested the library with Laravel 5.5. I'll have to check on this.

**Comment by mohamedbelhassen** [comment]
Could you please share an empty  Laravel Project (5.4) in which the library is correctly set?

**Comment by Parziphal** [comment]
Uh sorry, I didn't see your last reply earlier. I'll make the tests right now. But I was wondering, did you install the library, i.e. did you run `composer require parziphal/parse`?

**Comment by mohamedbelhassen** [comment]
I would like to thank you for the quick assistance.
I did not executed the mentioned instruction (composer require parziphal/parse).
I kindly request you to mention this instruction in the beginning of the setup section in order to easily assist beginners like me :).

**Comment by Parziphal** [comment]
You're right, I will include it in the readme. Thanks~
